from weasyprint import HTML
from jinja2 import Template
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

# HTML template for PDF generation with Arabic support
PDF_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Document Extraction Report - Batch #{{ batch_id }}</title>
    <style>
        @page {
            size: A4;
            margin: 2cm;
        }
        body {
            font-family: 'Noto Sans', 'Noto Sans Arabic', 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        .document {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .document-title {
            background-color: #3498db;
            color: white;
            padding: 8px 12px;
            margin-top: 20px;
            font-weight: bold;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .translated-section {
            margin-top: 15px;
        }
        .translated-title {
            background-color: #2ecc71;
            color: white;
            padding: 6px 10px;
            font-weight: bold;
            font-size: 12px;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #999;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .field-name {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <h1>Document Extraction Report - Batch #{{ batch_id }}</h1>
    <p><strong>Document Type:</strong> {{ doc_type|replace('-', ' ')|title }}</p>
    <p><strong>Report Date:</strong> {{ date }}</p>
    
    {% for card in cards_data %}
    <div class="document">
        <div class="document-title">Document #{{ card.index + 1 }}</div>
        
        <table>
            <thead>
                <tr>
                    <th>Field</th>
                    <th>Value</th>
                    <th>Confidence</th>
                </tr>
            </thead>
            <tbody>
                {% for field in card.fields %}
                <tr>
                    <td class="field-name">{{ field.name|replace('_', ' ')|title }}</td>
                    <td>{{ field.value }}</td>
                    <td>{{ (field.confidence * 100)|int }}%</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        {% if card.translated_fields %}
        <div class="translated-section">
            <div class="translated-title">Translated Data</div>
            <table>
                <thead>
                    <tr>
                        <th>Field</th>
                        <th>Translated Value</th>
                    </tr>
                </thead>
                <tbody>
                    {% for field in card.translated_fields %}
                    <tr>
                        <td class="field-name">{{ field.name|replace('_', ' ')|title }}</td>
                        <td>{{ field.value }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>
    {% endfor %}
    
    <div class="footer">
        Generated by Topnet Document Extraction System
    </div>
</body>
</html>
"""

async def generate_pdf(batch_id: int, doc_type: str, cards_data: list, output_path: Path):
    """Generate PDF using WeasyPrint (full Arabic support)"""
    try:
        template = Template(PDF_TEMPLATE)
        html_content = template.render(
            batch_id=batch_id,
            doc_type=doc_type,
            date=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            cards_data=cards_data
        )
        
        # Generate PDF
        HTML(string=html_content).write_pdf(output_path)
        logger.info(f"✅ PDF generated successfully with WeasyPrint: {output_path}")
        
        return True
        
    except Exception as e:
        logger.error(f"❌ WeasyPrint PDF generation failed: {e}")
        raise